services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"   # UI
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - otel-network

  service-a:
    build:
      context: ./services/service-a
      dockerfile: Dockerfile
    container_name: service-a
    ports:
      - "5001:8080"
    environment:
      - OTLP_ENDPOINT_URL=http://jaeger:4317
      - SERVICE_B_ENDPOINT_URL=http://service-b:8080/api
    depends_on:
      - jaeger
    networks:
      - otel-network

  service-b:
    build:
      context: ./services/service-b
      dockerfile: Dockerfile
    container_name: service-b
    ports:
      - "5002:8080"
    environment:
      - OTLP_ENDPOINT_URL=http://jaeger:4317
    depends_on:
      - jaeger
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge